apiVersion: v1
kind: Pod
metadata:
  labels:
    run: check-cm
  name: check-cm
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  containers:
    - image: nginx
      name: check-cm
      resources:
        # requests / limit が指定可能。ただし、
        # requests を省略した場合は、limits と同値になる
        limits:
          memory: 512Mi
          cpu: 500m
      # マウントされた cm のシェルを起動
      command: ["/config-vol/env.sh"]
      # cm を環境変数にする
      # ※ 環境変数とした場合、cm 自体を更新しても環境変数は同期されない
      # ※ Volume は定期的に同期される
      env:
        - name: SAMPLE_ENV
          valueFrom:
            configMapKeyRef:
              name: literal-cm
              key: sample_env
      # Volume マウント
      volumeMounts:
        - name: config-vol
          mountPath: /config-vol
  volumes:
    # Configmap / Secret は rw-r--r-- でマウントされる
    # ※ path で指定されたシンボリックリンクが作成される。元ファイルは上記のとおりとなる
    - name: config-vol
      configMap:
        name: literal-cm
        items:
          - key: env.sh
            path: env.sh
            # mode.. でパーミッションを指定できる
            mode: 0744 # ※ -rwxr--r--
