apiVersion: v1
kind: Pod
metadata:
  labels:
    run: check-pv
  name: check-pv
spec:
  containers:
    - image: nginx
      name: check-pv
      resources:
        # requests / limit が指定可能。ただし、
        # requests を省略した場合は、limits と同値になる
        limits:
          memory: 512Mi
          cpu: 500m
      volumeMounts:
        - name: nginx-pvc
          # Node 上の実際のパスは /mnt/data
          # ※ 意識する必要は無い
          mountPath: /mnt/pv
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: pvc
