apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: check-pv
  name: check-pv
spec:
  containers:
    - image: nginx
      name: check-pv
      volumeMounts:
        - name: nginx-pvc
          # Node 上の実際のパスは /mnt/data
          # ※ 意識する必要は無い
          mountPath: /mnt/pv
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: pvc
