apiVersion: v1
kind: Pod
metadata:
  labels:
    run: empty-dir
  name: empty-dir
spec:
  containers:
    - image: nginx
      name: empty-dir
      resources:
        # requests / limit が指定可能。ただし、
        # requests を省略した場合は、limits と同値になる
        limits:
          memory: 512Mi
          cpu: 500m
      volumeMounts:
        - mountPath: /cache
          name: cache-vol
  volumes:
    - name: cache-vol
      # 一時ディレクトリを作成する
      emptyDir:
        # 以下 medium の指定で tmpfs を指定可
        medium: Memory
        # ダミーのファイル（Null文字埋め）を作成して上限確認
        # dd if=/dev/zero of=/cache/dummy bs=1M count=129
        sizeLimit: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
