apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mounted-pod
  name: mounted-pod
spec:
  containers:
    - image: nginx
      name: mounted-pod
      resources:
        # requests / limit が指定可能。ただし、
        # requests を省略した場合は、limits と同値になる
        limits:
          memory: 512Mi
          cpu: 500m
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      secret:
        secretName: db-auth
        # items を明示すると、明示したキーだけをマウントする
        # items:
        #   - key: username
        #     path: username.txt
  restartPolicy: Never
