apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: pod
spec:
  containers:
    - image: nginx
      name: pod
      resources:
        requests:
          memory: 512Mi
          cpu: 500m
        limits:
          memory: 1024Mi
          cpu: 1000m
      # # secret をまとめて追加する場合は以下
      # # env -> envFrom
      # # ※ 個々を指定する版と比較して、`name` が無い
      # envFrom:
      #   # インデントに注意 -> name / prefix
      #   - secretRef:
      #       name: db-auth
      #     prefix: DB_AUTH_
      env:
        - name: DB_USER_NAME
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: username
  restartPolicy: Never
