apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  # 同一名称 "manual" の pv をバインドする
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
#
# pvc を dry-run する方法は無いらしい。k8s 公式からの取得を推奨
# -----
# $ curl -sSL https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/storage/pv-claim.yaml
#
