apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy
  name: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
    spec:
      containers:
        - image: amsy810/tools
          name: hpa
          resources:
            # requests / limit が指定可能。ただし、
            # requests を省略した場合は、limits と同値になる
            limits:
              memory: 200Mi
              cpu: 100m
