apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
        - name: php-apache
          # k8s 公式デモのイメージ
          image: k8s.gcr.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  ports:
    - port: 80
  selector:
    run: php-apache
#
# 以下を参照して hpa の負荷を観察する
# [CPU 負荷を与える](https://kubernetes.io/ja/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#%E8%B2%A0%E8%8D%B7%E3%81%AE%E5%A2%97%E5%8A%A0)
#
